version: "3"

services:
  next-app:
    container_name: playground-nico-fyi
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_URL: ${DATABASE_URL}
    restart: always
    ports:
      - 3000:3000
