import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(inter.className, "min-h-screen")}>
        {children}
        <div className="text-sm text-muted-foreground text-center sticky bottom-0 bg-background">
          The source code for this playground is in{" "}
          <a
            className="underline"
            href="https://github.com/nicnocquee/playground.nico.fyi"
          >
            https://github.com/nicnocquee/playground.nico.fyi
          </a>
        </div>
      </body>
    </html>
  );
}
